services:
  # phpMyAdmin jen lokálně / podle potřeby
  phpmyadmin:
    image: phpmyadmin:5
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: ${SUITECRM_DB_PORT}
      PMA_USER: ${SUITECRM_DB_USER}
      PMA_PASSWORD: ${SUITECRM_DB_PASSWORD}
      UPLOAD_LIMIT: 64M
    ports:
      # můžeš si změnit host port bez zásahu do .env
      - "${PMA_PORT_HOST:-8081}:80"
    depends_on: [db]
    networks: [suitecrm]

  # Lokální ladění PHP (Xdebug apod.)
  app:
    environment:
      # zapni/ vypni dle potřeby
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 idekey=PHPSTORM
    # Volitelně lokální php.ini
    # volumes:
    #   - ./ops/php/php.ini:/usr/local/etc/php/conf.d/99-local.ini:ro

  # Pohodlnější file-watching na macOS/Windows (Vite/Nuxt)
  node:
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"

  # Pokud jsi na Linuxu a chceš mít host.docker.internal:
  # web:
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  # app:
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
