name: ${SUITECRM_PROJECT_NAME}

services:
  web:
    image: nginx:1.27-alpine
    depends_on:
      app:
        condition: service_started
    ports:
      - "${SUITECRM_WEB_HOST:-127.0.0.1}:${SUITECRM_WEB_PORT_HOST:-8080}:80"
    environment:
      SITE_URL: "http://${SUITECRM_WEB_HOST:-localhost}:${SUITECRM_WEB_PORT_HOST:-8080}"
    volumes:
      - ./:/var/www/html
      - ./ops/nginx/conf.d:/etc/nginx/conf.d:ro
      - uploads:/var/www/html/public/legacy/upload
    networks: [suitecrm]

  app:
    build:
      context: .
      dockerfile: ops/php/Dockerfile
      args:
        SKIP_FE: "0"
    environment:
      DB_HOST: db
      DB_PORT: ${SUITECRM_DB_PORT}
      DB_NAME: ${SUITECRM_DB_NAME}
      DB_USER: ${SUITECRM_DB_USER}
      DB_PASSWORD: ${SUITECRM_DB_PASSWORD}
      REDIS_HOST: ${SUITECRM_REDIS_HOST}
      REDIS_PORT: ${SUITECRM_REDIS_PORT}
      SMTP_HOST: ${SUITECRM_SMTP_HOST}
      SMTP_PORT: ${SUITECRM_SMTP_PORT}
      ELASTIC_HOST: ${SUITECRM_ELASTIC_HOST}
      ELASTIC_PORT: ${SUITECRM_ELASTIC_PORT}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      AUTH_TYPE: ${AUTH_TYPE}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
      SITE_URL: "http://${SUITECRM_WEB_HOST:-localhost}:${SUITECRM_WEB_PORT_HOST:-8080}"
    volumes:
      - ./:/var/www/html
      - uploads:/var/www/html/public/legacy/upload
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      elasticsearch:
        condition: service_started
    networks: [suitecrm]

  scheduler:
    build:
      context: .
      dockerfile: ops/php/Dockerfile
    command: [ "sh", "-lc", "while true; do php -f public/legacy/cron.php; sleep 60; done" ]
    environment:
      DB_HOST: db
      DB_PORT: ${SUITECRM_DB_PORT}
      DB_NAME: ${SUITECRM_DB_NAME}
      DB_USER: ${SUITECRM_DB_USER}
      DB_PASSWORD: ${SUITECRM_DB_PASSWORD}
      REDIS_HOST: ${SUITECRM_REDIS_HOST}
      REDIS_PORT: ${SUITECRM_REDIS_PORT}
    volumes:
      - ./:/var/www/html
      - uploads:/var/www/html/public/legacy/upload
    depends_on:
      app:
        condition: service_started
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks: [suitecrm]

  db:
    image: mariadb:11.4
    environment:
      MARIADB_DATABASE: ${SUITECRM_DB_NAME}
      MARIADB_USER: ${SUITECRM_DB_USER}
      MARIADB_PASSWORD: ${SUITECRM_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${SUITECRM_DB_ROOT_PASSWORD}
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--skip-name-resolve"
    ports:
      - "${SUITECRM_WEB_HOST:-127.0.0.1}:${SUITECRM_DB_PORT_HOST:-3308}:${SUITECRM_DB_PORT:-3306}"
    volumes:
      - ./.data/${SUITECRM_PROJECT_NAME:-suitecrm}/mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin -h 127.0.0.1 -uroot -p$$MARIADB_ROOT_PASSWORD ping --silent"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks: [ suitecrm ]

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "${SUITECRM_WEB_HOST:-127.0.0.1}:${SUITECRM_REDIS_PORT_HOST:-0}:${SUITECRM_REDIS_PORT:-6379}"
    networks: [suitecrm]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${SUITECRM_ELASTIC_VERSION}
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "${SUITECRM_WEB_HOST:-127.0.0.1}:${SUITECRM_ES_PORT_HOST:-9201}:${SUITECRM_ELASTIC_PORT:-9200}"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks: [suitecrm]

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "${SUITECRM_WEB_HOST:-127.0.0.1}:${SUITECRM_MAILHOG_PORT_HOST:-8025}:8025"
    networks: [suitecrm]

  node:
    image: node:20-alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - node_modules:/workspace/node_modules
    environment:
      HOST: "0.0.0.0"
      PORT: "${SUITECRM_NODE_DEV_PORT}"
      NUXT_HOST: "0.0.0.0"
      NUXT_PORT: "${SUITECRM_NODE_DEV_PORT}"
    ports:
      - "${SUITECRM_WEB_HOST:-127.0.0.1}:${SUITECRM_NODE_DEV_PORT_HOST:-5173}:${SUITECRM_NODE_DEV_PORT:-5173}"
    networks: [suitecrm]

volumes:
  uploads:
    name: "${SUITECRM_PROJECT_NAME}_uploads"
  redis_data:
    name: "${SUITECRM_PROJECT_NAME}_redis_data"
  es_data:
    name: "${SUITECRM_PROJECT_NAME}_es_data"
  node_modules:
    name: "${SUITECRM_PROJECT_NAME}_node_modules"

networks:
  suitecrm:
    name: ${SUITECRM_PROJECT_NAME}_net
    driver: bridge
