services:
  phpmyadmin:
    image: phpmyadmin:5
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: ${SUITECRM_DB_PORT}
      PMA_USER: ${SUITECRM_DB_USER}
      PMA_PASSWORD: ${SUITECRM_DB_PASSWORD}
      UPLOAD_LIMIT: 64M
    ports:
      - "${SUITECRM_WEB_HOST:-localhost}:${SUITECRM_PHPMYADMIN_PORT:-8081}:80"
    depends_on: [db]
    networks: [suitecrm]

  app:
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 idekey=PHPSTORM
    # volumes:
    #   - ./ops/php/php.ini:/usr/local/etc/php/conf.d/99-local.ini:ro

  node:
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"

  # Pokud jsi na Linuxu a chceš mít host.docker.internal:
  # web:
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  # app:
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
